# Generated by Django 4.2.6 on 2023-10-08 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_id_from_telegram',
            field=models.PositiveSmallIntegerField(blank=True, null=True, unique=True),
        ),
    ]
