# Generated by Django 4.2.6 on 2023-10-08 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0003_tokenproxy'),
        ('api', '0002_alter_customuser_user_id_from_telegram'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomToken',
            fields=[
                ('token_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='authtoken.token')),
                ('user_id_from_telegram', models.PositiveSmallIntegerField(unique=True)),
            ],
            bases=('authtoken.token',),
        ),
    ]
